
from pathlib import Path

file_path = Path(__file__).parent / "Harsha.txt"

f = open(file_path,"r")

content = f.read()

print(content)

f.close() # if we use open then we must close it


# from pathlib import Path

# file_path = Path(__file__).parent / "Harsha.txt"

# print(file_path)

# with file_path.open("r", encoding="utf-8") as file:
#     content = str(file.read())

# print(content)



# Code Generated by Sidekick is for learning and experimentation purposes only.
# filename: read-harsha-file.py
